---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^wet/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-added-large-files
  - id: check-case-conflict
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.git
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping=2, --sequence=2, --offset=0]
- repo: local
  hooks:
  - id: hydrate-kustomize
    name: Hydrate kustomize yaml
    entry: pre_commit_hooks/hydrate_kustomize.py
    language: python
    always_run: true
    pass_filenames: false
    additional_dependencies: [gitpython>=3.1]
  - id: kubeconform
    name: kubeconform
    entry: kubeconform -strict -ignore-missing-schemas -summary -kubernetes-version 1.24.0 -n 12 wet
    language: system
    always_run: true
    pass_filenames: false
