---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: logging
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 4Gi
    limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resources
  namespace: logging
spec:
  hard:
    requests.storage: 100Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: logging
spec:
  hard:
    configmaps: '100'
    secrets: '100'
    services: '100'
    pods: '100'
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-and-memory
  namespace: logging
spec:
  limits:
  - type: Container
    min:
      cpu: 25m
      memory: 32Mi
    max:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 256Mi
    default:
      memory: 256Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: logging
automountServiceAccountToken: false
