---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml

helmCharts:
- name: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: v2.6.1
  releaseName: loki
  namespace: logging
  valuesInline:
    loki:
      enabled: true
      rbac:
        pspEnabled: false
    promtail:
      enabled: true
      rbac:
        pspEnabled: false
    grafana:
      enabled: true
      rbac:
        pspEnabled: false
      admin:
        existingSecret: loki-grafana
