apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: logging
spec:
  hard:
    limits.memory: 4Gi
    requests.cpu: 4000m
    requests.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: logging
spec:
  hard:
    configmaps: "100"
    pods: "100"
    secrets: "100"
    services: "100"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resources
  namespace: logging
spec:
  hard:
    requests.storage: 100Gi
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: default
  namespace: logging
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-and-memory
  namespace: logging
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      cpu: 500m
      memory: 256Mi
    max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 25m
      memory: 32Mi
    type: Container
